export enum CATEGORY {
    LEVEL1 = 'LEVEL1',
    LEVEL2 = 'LEVEL2',
    LEVEL3 = 'LEVEL3',
}

export enum REQUIRED_NOTE {
    CHOTHUHANG = 'CHOTHUHANG',
    CHOXEMHANGKHONGTHU = 'CHOXEMHANGKHONGTHU',
    KHONGCHOXEMHANG = 'KHONGCHOXEMHANG',
}
