#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../@openapi-contrib/openapi-schema-to-json-schema/dist/bin.js" "$@"
  ret=$?
else 
  node  "$basedir/../@openapi-contrib/openapi-schema-to-json-schema/dist/bin.js" "$@"
  ret=$?
fi
exit $ret
